### PR TITLE
Coordinator dashboard

### LINKED ISSUE #612: Create coordinator dashboard
### Overview
A simple implementation of the coordinator dashboard and table. This will include:

- An updated route for the coordinator dashboard.
- A data table that displays  applications with status and details such as applicant. type -guest and host , coordinator assigned, Application status and notes.
- Search and filter options to  filter by applicant type , status and coordinator info
- Option for coordinator to assign the application to one of the coordinators( dropdown)

### PR DESCRIPTION
**Pull request by erikguntner**
Closes #612 

### What changes did you make?
  - Replaced the coordinator dashboard page with an updated layout
  - Added a data grid component to the dashboard that renders dummy data created with faker.js
  - Created a custom pagination component
  - Added guest invite component to new dashboard
  - Added faker.js as a dependancy. This allows us to easily create dummy data while endpoints are still being worked on
  - Table has an editable notes column
### Rationale behind the changes?
  - The coordinator dashboard needed to be updated with a new layout
  - I wanted to get an initial implementation of the data table up so we could start thinking about what data we need to store and fetch for each user
### Testing done for these changes
  - Decided to wait on testing until we are fetching data from an end point. Most of what is done here is passing dummy data to a Material UI component which controls most of the behavior. 
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-10-05 at 3 42 13 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-10-05 at 3 37 25 PM

</details>

### CODE REVIEW

**Comment by Joshua-Douglas** [comment]
Hey @erikguntner, 

When I decrease the width of the browser window the grid slow grows for an indefinite amount of time. I get this same effect when using the developer device toolbar and switching to a mobile device. 

https://github.com/hackforla/HomeUniteUs/assets/22138019/4f91e93c-0e81-4ff2-90f1-577dccb2b340

Do you see this same effect?

**Review by JpadillaCoding — COMMENTED** [review]
I am also getting the infinite grow effect as Joshua. 
Also found a minor bug when an item is selected on a tab, if navigating to another tab sometimes the checked item is unchecked. This seems to only happen when checking an item and then navigating to another tab that doesn't have that item. 
This doesn't really impede the functionality of the dashboard and can see this being a bug ticket for later on. 

https://github.com/hackforla/HomeUniteUs/assets/104275658/5cbe3ea6-92e3-4731-844f-027617f2965d

**Comment by erikguntner** [comment]
@Joshua-Douglas @JpadillaCoding Thanks for bringing this to my attention. I fixed the problem with the growing effect, but the tabs dimensions are too big for mobile screens, so those will have to be fixed in the future. I'm gonna leave it as is for now since we don't have mobile designs at the moment, but I'll let design know.

**Comment by erikguntner** [comment]
@JpadillaCoding I see what you mean. Thanks for pointing this out! I imagine this happens because the table is no longer tracking the state of the item once it's filtered out. I'm not sure if this is a bug or not since I don't know if we wanna track state for items that aren't currently in the table, but we can keep our eyes on it.

**Review by JpadillaCoding — APPROVED** [review]

**Pull request merged**
