### PR TITLE
Update guest invite and guest confirmation flows

### LINKED ISSUE #405: Section 1 | Subflow 1b: Coordinator Invite Guests
### The Problem:

Currently, Coordinators do not have a way to invite Guests to create an account. As a result, Guests cannot create an account or profile on Home Unite Us, which are required steps to find housing on the platform.

#### User Story:

As a Coordinator, I want to create an account for the Guest and invite the Guest to Home Unite Us, so that the Guest can begin the application and onboarding process.

### High Level Approach:

Allow Coordinators to create accounts for Guests and invite Guests to confirm their Home Unite Us accounts.

### Goals & Success:

Success is if Coordinators can create Guest accounts and send Guests invitations to confirm the account.

### Key Features:

* A button on the Coordinator home page to invite Guests
* Field to enter a Guest email address
* A verification email containing a verification link that is sent to the Guest email address

### Acceptance Criteria:

* Coordinators can invite Guests via email from the Coordinator homepage
* A verification email will be sent to the email address containing a verification link
   * The verification link expires after 2 weeks maximum
* The user flow can be complete on desktop, mobile, and tablet

### Designs:

- [ ] Review existing designs on Figma
- [ ] Edit existing designs as needed and share a link to the updated designs in this issue

### Open Questions:

* Support email, SMS, or both in the first version?
* What happens after the link expires?
   * Option to request a new link from the Coordinator?
* What are the data tables that are needed and associated schemas?
   * Are these blocking for this phase of work?

### LINKED ISSUE #440: Section 1 | SubFlow 1c: Guest Account Confirmation
### The Problem:

Currently, Guests do not have a way to create an account for Home Unite Us. As a result, Guests cannot access Home Unite us to create a profile, which is a required step to find housing on the platform.

#### User Story:

As a Guest, I want to confirm my Home Unite Us account, so that I can log in to Home Unite Us and begin the application (Intake Profile) and onboarding process.

### High Level Approach:

Allow Guests to create an account after receiving an invitation from Coordinators.

### Goals & Success:

Success is if Guests can receive an account creation invitation email from Coordinators and create an account on Home Unite Us.

### Key Features:

* Email containing a temporary password and invitation link that redirects users to a set password page

### Acceptance Criteria:

* Users can open the validation email and click the link
* The validation email will contain a temporary password
* Clicking the validation link will confirm the user account and redirect the user to a set password page
   * After entering the temporary password, the user will be redirected to the set password page
   * The set password page will have the same behavior as the reset password page in #442 
* The user flow can be completed across desktop, mobile, and tablet

### Designs:

- [ ] Review existing designs on Figma
- [ ] Edit existing designs as needed and share a link to the edited designs in this issue

### Key Decisions:

* After successfully logging in for the first time, the user will be redirected to the app (versus the default redirect to an AWS page). The rationale is that users will have a better first experience with the app if redirected to the app versus the AWS page. This will require additional dev effort - if significant dev effort is needed will revisit.

### Open Questions:

* Support SMS in addition to email in the first version?

### PR DESCRIPTION
**Pull request by erikguntner**
Closes #405
Close #440

### What changes did you make?

The following changes allow coordinators to invite guests to HUU by filling out a short form and sending an invitation link to the provided email. The guest can then accept the invite by clicking the provided link and confirm their account by creating a new password. This PR builds off the work that was done in #558 by handling some edge cases and writing tests. The changes include:

- Adding a separate endpoint to handle accepting invites. The original flow had users receiving a temporary password they would use to sign in before being prompted to create a new one. This meant the `/auth/signin` endpoint handled signing in normally, as well as signing in with a temporary password. In an effort to streamline the process and simplify logic, I used a lambda function to add a link to the email and create a separate endpoint that handles signing in with the temporary password. If the user accepts the invite successfully, they are redirected to the new password page, and a `userId` and `sessionId` are included in the URL params. These two params then get passed along when creating their new password in order to complete the flow. If unsuccessful, an error message is included in the URL params and displayed to the user.
- Adding a success message after a guest is successfully invited.
- Adding alerts for errors and loading states on buttons.
- Some small refactors to make sure the existing services were hitting the right endpoints and sending the correct data

### Rationale behind the changes?
After merging #558 I noticed there was still work needed in order to get the invite guest and guest confirmation user flows working properly.  These changes allow both flows to be completed.

### Testing done for these changes
  - I wrote unit tests for the guest invite button component
  - I wrote Cypress tests for the new password page to confirm the `userId`, `sessionId`, and `error` params were successfully being accessed from the URL and that the user's session starts after creating a new password.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

https://github.com/hackforla/HomeUniteUs/assets/27253583/b4560da6-a1f5-48b3-9816-c5504a124644

Screenshot 2023-11-14 at 6 44 55 PM

https://github.com/hackforla/HomeUniteUs/assets/27253583/049a6932-2d98-43c0-8f12-a366b4d26572

</details>

### CODE REVIEW

**Comment by JpadillaCoding** [comment]
Hey Erik, was there a way you could test the signup feature from the email on local?

**Comment by erikguntner** [comment]
@JpadillaCoding Are you trying to test out the flow on your machine?  I think the only way you could test the sign up locally would be by sending an invite to an email you have access to.

**Comment by JpadillaCoding** [comment]
Gotcha, so while trying to test it out I get an error `CustomMessage failed with error Cannot read properties of undefined (reading 'url')`. 
I was wondering if this was maybe because it is being tested locally or not. Are you getting the same message? 
Also note that attempting to send it again after that error results in the error `an account with the given email already exists.` So it seems that It is going through on our end but not actually sending.

**Comment by erikguntner** [comment]
@JpadillaCoding I just went through the sign up using an email flow and invite guest flow on my computer with no issues.

>  so while trying to test it out I get an error CustomMessage failed with error Cannot read properties of undefined (reading 'url')

This error may be because you are not passing a url in the request. This could be an issue with the .env not having a proper url, but I'm not sure.

> Also note that attempting to send it again after that error results in the error an account with the given email already exists. 

There is a way to resend an invite to an existing user by passing `MessageAction='RESEND',` to the boto3 client this just hasn't been implemented yet. I can't remember exactly what we decided as far as how we want to handle resends. I'll look through some of the issues and bring it up to PM if I can't find anything.

**Review by JpadillaCoding — APPROVED** [review]
After testing the feature everything works as expected. A user can invite a guest, the guest can accept the invitation and create a new password, the new account is added to the DB and the account is active. 
No suggestions as far as the code, everything looks good!

**Pull request merged**
