### PR TITLE
NavMobile landing page side bar links

### LINKED ISSUE #579: Mobile Landing Page Login, Sign Up
### Expected behavior

On the pre-login landing page (dev.homeunite.us) on mobile, after clicking the hamburger menu:

- When clicking on login, expect to be forwarded to a login screen
- When clicking on Sign Up expected to be forwarded to a sign up screen

### Observed behavior

- When clicking on Login, nothing happens
- When clicking on Sign Up nothing happens

Screen capture of [bug](https://hackforla.slack.com/files/UJK101BKL/F05PV6ELW3B/huu-mobilenavbarbug.mp4) (thanks Joshua!)

### PR DESCRIPTION
**Pull request by mira-kine**
Closes #579 

### What changes did you make?
  - Added href to list item button in the drawer as well

### Rationale behind the changes?
  - current link was only used in the HUU Logo button, not the hamburger menu drawer
  
### What did you learn or can share that is new?(optional)
  - coordinator/host icon responsiveness will be changed in another issue
  - nav mobile has both hamburger and HUU icon working as nav (maybe a merge bug?). Since issue #552 was about replacing hamburger menu with HUU icon, I think this is another bug but wanted to make sure since I see a [double menu proposal on Figma](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=370%3A0&mode=dev) as well.

<details>
<summary>Visuals before changes are applied</summary>

[Original Bug](https://hackforla.slack.com/files/UJK101BKL/F05PV6ELW3B/huu-mobilenavbarbug.mp4)

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
https://github.com/hackforla/HomeUniteUs/assets/90009901/fc1cebf8-7e8b-4d56-8cdf-133422bf251c

</details>

### CODE REVIEW

**Review by tylerthome — APPROVED** [review]

**Comment by Joshua-Douglas** [comment]
Hey @tylerthome, @erikguntner, 

It looks like we accidentally merged this PR with a failing CI pipeline. Can we add some branch protections to require the status checks to pass?

I'll submit a fix for this in #668. 

Thanks!

**Comment by JpadillaCoding** [comment]
@Joshua-Douglas Do you believe this is what may be causing other PR checks to fail? I've been experiencing failures and couldn't figure out why and I see that your checks have now turned into failures too.

**Comment by Joshua-Douglas** [comment]
Hey @JpadillaCoding, Yes it is! I took a look at your pipeline failure on PR #671 and I can confirm it is the same issue.

I fixed the error in [74f861e](https://github.com/hackforla/HomeUniteUs/pull/668/commits/74f861e4e8bf16b52a9cc5cffa2e0607e23cba9c). You should be able to cherry-pick this commit onto your branch to fix the error. Or you can wait for my PR to be merged and then merge with `main`. Both options work!

**Comment by JpadillaCoding** [comment]
@Joshua-Douglas Yup that fixed it for me! Nice job figuring this out and I also got to learn about git cherry-pick which was neat too 😄

**Comment by Joshua-Douglas** [comment]
That's awesome!!

**Pull request merged**
