### PR TITLE
Member Onboarding Issue Template

### PR DESCRIPTION
**Pull request by JRHutson**
Created a template for creating issues to track new member on boarding.

### CODE REVIEW

**Comment by JRHutson** [comment]
I thought it might be good to have an issue associated with each new member onboarding that we could use to make sure people don't get lost in the process. Let me know if this strategy makes sense.

Also, please look at the items in the check list to make sure they are comprehensive and relevant.

**Review by quyenvhle — COMMENTED** [review]
#All members:
[ ] - Added to Slack channel #home-unite-us.
[ ] - Reviewed HUU progress (need to create an issue for this/direct new members to somewhere to see the progress).

#Developers:
[ ] - Added to Slack channel #home-unite-us-dev.

#Design:
[ ] - Added to Slack channel #home-unite-us-design.
[ ] - Reviewed [Calendaring Figma] (https://www.figma.com/file/FrIY32ZqKGJxl3VQNoGgPg/Calendaring-Home-Unite-Us?node-id=140%3A410) for reference.

#Product Management:
[ ] - Added to Slack channel #home-unite-us-dev.
[ ] - Added to Slack channel #home-unite-us-design.

**Comment by JRHutson** [comment]
@quyenvhle The Slack channels are great callouts. Could you elaborate on what you're thinking regarding reviewing progress? Is that something that can be encompassed in an issue or will it need to be part of someone's initial engagement for the lead in their specialty?

**Comment by quyenvhle** [comment]
@JRHutson that's a better approach. We could add "Meet with lead" as a bullet point on this template.

**Pull request merged**
