### PR TITLE
Guest form components for application process

### LINKED ISSUE #644: Guest Form Components: Welcome, Expectations, Basic Information
**Overview**

Create the first three guest application forms for the guest application workflow including the welcome page, guest expectations, and basic info forms. Incorporate with guest application context file to update state. Add routes to context wrapper in main.tsx. 

The guest form state is being stored by context and the guest application buttons contain the save form functionality so any additional handle submit functionality is not needed in each application form. The form is being used for updating the context values and allowing button functionality for submission on each step. 

Another ticket may be needed for local storage for offline support in the future. 

**Action Items**

- [ ] Create Welcome Form
- [ ] Create Expectations Form
- [ ] Create Basic Info Form
- [ ] Use figma to verify text and design
- [ ] Update stepper to include these forms for guest context wrapper
- [ ] Update main.tsx to include form routes within guest application context wrapper
- [ ] Update Guest Application Context to include form routes for stepper 
- [ ] Update Guest Application Tracker to allow for route access to guest forms.

### Resources/Instructions
#533 Section 2 | Guest Application Form
#630 Guest Application Stepper- Context Wrapper
#610 Guest Application Implementation
[Fimga](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?type=design&node-id=16-2646&mode=design&t=4HlPEnoUogsLL0Ji-0)

### PR DESCRIPTION
**Pull request by johnwroge**
Closes #644

### What changes did you make?

- Created the first three form elements for the guest application workflow including a welcome, expectations, and basic form.

-  Updated the guest application tracker to 'in progress' to allow for the application to be accessed. 

- Added a route element to the guest application context wrapper to allow for the forms to be accessed within the stepper component and updated the stepper to include these forms. 

- These changes were built from Jose's existing branch detailed in #640

  
### Rationale behind the changes?

   Forms are needed for guests to enter their personal information for the guest application process. They are needed to 
store the values in the context file to eventually be sent to the backend API when it is ready to be connected. 

  The routes needed for this workflow were added to the main.tsx file so they are accessible to the user and developer. I updated two components ( to allow access from both the nav bar and guest application tracker. 

  - ### Testing done for these changes
  - Tests were run in the frontend and backend directories to verify no side effects with existing sections. 
  - Context values were tested to show they were being updated based on form input.
  - Additional unit tests will need to be added in a separate pull request. 
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
N/A
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

https://github.com/hackforla/HomeUniteUs/assets/72668920/c7047558-c19c-4068-a0e2-087bb72d48b1

image

</details>

### CODE REVIEW

**Comment by JpadillaCoding** [comment]
Hey John, I took a look at the PR from a functionality standpoint and disregarded any design modifications since they're still being worked on. 

One thing that needs to be done for each form is that we need to handle errors since the data is being validated. For example, if a user did not fill out a field or if something was not formatted correctly then the form needs to notify them of that. 

I built out a schema that can be found ``utils/GuestApplicationSchema.ts``. Note that the schema is an array with each iteration correlating to the step the form is on and would need to be modified to match the questions being asked. I've set the schema questions with the current designs, but as the design changes then the validation schema needs to be updated to match which questions are being asked per page and also what each question validates for needs to be updated.
Here's an example using the error handler along with helper text that guides the user to what is wrong. 
```jsx
<TextField
  fullWidth                   
  id="fullName"
  name="fullName"  
  label="Full Name"           
  value={fullName}            
  onChange={handleChange}
  onBlur={handleBlur}         
  error={touched.fullName && Boolean(errors.fullName)}
  helperText={touched.fullName && errors.fullName}      
/>
```
This also raises the question of how the design team wants to handle showing error messages. I've made a comment on the figma file for clarification. One more thing of note is that since the schema file is an array correlating to the current step, I needed to add two nulls to the array to correlate to the welcome and expectations page so that the validation will work.
Here is what adding the errors and helper text would look like. 
Screenshot 2024-02-14 at 10 07 43 PM

**Comment by erikguntner** [comment]
@johnwroge this all looks good to me. The only request I have is to please add the forgot password code tests back to the repo before we merge this. Instead, just skip them or comment them out so we still have them for the future when we get the testing issue figured out.

**Comment by johnwroge** [comment]
Thanks @erikguntner, I added the tests back in. I must have deleted that file and forgot to add it back in.

**Comment by erikguntner** [comment]
Thanks @johnwroge. All good

**Review by erikguntner — APPROVED** [review]

**Pull request merged**
