### PR TITLE
Fix API Test Case Failures

### PR DESCRIPTION
**Pull request by Joshua-Douglas**
The API test cases are failing with this error: `jsonschema.exceptions.RefResolutionError: unknown url type: './paths/users.yaml'`.

The root cause of this failure was in `BastTestCase.create_app`. There is a known issue related to the application specification in 
#539. The specification file cannot contain references to other files, so our flask app should use the `openapi_server/_spec/openapi.yaml` file. The test app, however, was using the `openapi_server/openapi/openapi.yaml` file instead.

Unfortunately, when I made this fix I found several other failing test cases and some other sources of testing errors. This PR contains the minimum fixes needed to get the test cases passing again. I refrained from making any design changes at this point.

Here are a summary of the fixes:
* Fix an `AttributeError` in `service_provider_controller.py`'s `create_service_provider()` method. The test cases were failing with a status code of `500` since an unhandled exception was being thrown here
* Fix `Instance not bound to session` err that was being thrown while creating a service provider. Test cases were failing with a status code of `500` here too.
  * The database row id was being read after calling `session.close()`. This is not a problem if the session has been flushed, but by default SQLAlchemy will lazily load the row, so attempting to read after closing the session can cause an error. To fix I just read the row id before closing.
* Fix return syntax error in `get_service_provider_by_id` and `update_service_provider`. These methods were not returning the correct status code if the provider search failed
* Add an error status code to `delete_service_provider` if the provider deletion fails. Our test cases were passing, even though no deletion was occuring, since we were always passing back a successful status code
* Update the controller test cases to use a temporary testing database. Previously the test cases were operating on the host's local database. This means that the tests would only pass if the host happened to have a database with a sufficient number of entries. The new test setup has the added benefit of making the controller test cases independent of each other.
  * Note: Our Flask app interface does not allow the ability to specify a custom database, so I had to hack it a bit. Ideally we'd redesign our interface with testing in mind - but I wanted to limit the scope of this issue 
* Fix syntax error in `HousingProviderRepository.__init__`. Default args are only evaluated when the method definition is executed, so move the call to `get_engine` into the method body. 
* remove `test_match_filtering.py`. This file was empty and unused

### CODE REVIEW

**Comment by Joshua-Douglas** [comment]
Just a heads up - the PR build failed the first time I sent it off. I think it is a sporadic, unrelated failure. 

Here was the error in the `npm run test` stage. The build passed when I restarted it.

Thanks!

```
 ❯ src/views/__tests__/ForgotPasswordCode.test.tsx:55:5
     53| 
     54|     expect(screen.queryByRole('alert')).not.toBeInTheDocument();
     55|     waitFor(() => expect(screen.getByRole('form')).toBeInTheDocument()…
       |     ^
     56|   });
     57| 
 ❯ node_modules/@vitest/runner/dist/index.js:160:13
 ❯ node_modules/@vitest/runner/dist/index.js:41:26
 ❯ runTest node_modules/@vitest/runner/dist/index.js:491:17
 ❯ runSuite node_modules/@vitest/runner/dist/index.js:594:15
 ❯ runSuite node_modules/@vitest/runner/dist/index.js:594:15
 ❯ runFiles node_modules/@vitest/runner/dist/index.js:645:5
 ❯ startTests node_modules/@vitest/runner/dist/index.js:655:3
 ❯ node_modules/vitest/dist/entry.js:276:7

This error originated in "src/views/__tests__/ForgotPasswordCode.test.tsx" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "display an error message". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- This was the last recorded test before the error was thrown, if error originated after test finished its execution.
Error: Process completed with exit code 1.
```

**Review by paulespinosa — APPROVED** [review]
The changes look good. Thank you.

**Comment by paulespinosa** [comment]
@Joshua-Douglas I also noticed that the npm tests fail sporadically.

**Comment by erikguntner** [comment]
@Joshua-Douglas @paulespinosa I'll take a look at the tests. It seems to be that same one that fails randomly.

**Review by erikguntner — APPROVED** [review]

**Comment by ju1es** [comment]
sweet, thank you for fixing these! awesome test scaffolding. I'm not used to writing tests for endpoints that aren't part of a testable class which is why I pulled a lot of the logic out into the repository class. 

preemptively approving but just one question below,

> Fix syntax error in HousingProviderRepository.__init__. Default args are only evaluated when the method definition is executed, so move the call to get_engine into the method body.
i'm not a pythonista so just want to clarify, is the function application in the body also evaluated during function execution?

**Review by ju1es — APPROVED** [review]

**Comment by Joshua-Douglas** [comment]
> i'm not a pythonista so just want to clarify, is the function application in the body also evaluated during function execution?

Hey, happy to clarify! The body is  executed each time the function is called, but the default arg assignment only happens once. 

The general rule for default args is that they should be set to an immutable type, since otherwise the default arg will be a reference to a mutable object that may change each time the function is called. This leads to unexpected behavior, so 'None' is typically used in place of a default mutable type.

Here are some examples the demonstrate the weird behavior.

I hope these help! If not I'm sure I can find an article to explain it better.
'''
def append_print(el, lst=list()):
    lst.append(el)
    print(lst)
    
append_print(1) # print [1]
append_print(2) # print [1,2]?!
append_print(3, list()) # print [3]

class DBLayer:
    engine = None
    
def print_engine(eng=DBLayer.engine):
    print(eng)
    
print_engine() # None, as expected 
DBLayer.engine = "Fancy engine"
print_engine() # Still None!!
print_engine(DBLayer.engine) # Prints "Fancy engine"
'''

**Pull request merged**
